apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-c1742387315858
  janus-idp.io/tekton: codegen-c1742387315858
  backstage.io/kubernetes-id: codegen-c1742387315858
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegen-c1742387315858
resources:
  - application-dev.yaml
