apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: codegen-c1742387315858
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-c1742387315858
  name: codegen-c1742387315858
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
