apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: codegen-c1742387315858
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-c1742387315858
  name: codegen-c1742387315858
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: codegen-c1742387315858
